#Import the Data

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
attorney = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/attorneys.csv")
attTimeEntires = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/attorneytimeentries.csv")
cat = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/categories.csv")
client = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/clients.csv")
questionP = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/questionposts.csv")
questions = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/questions.csv")
statesite = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/statesites.csv")
subcat = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/subcategories.csv")

<ipython-input-247-6befc2724c31>:5: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  questionP = pd.read_csv("/content/drive/Shareddrives/Data Fest 2023/data/questionposts.csv")

In [ ]:
attorney.head()

,Id,StateAbbr,AttorneyUno,City,County,StateName,PostalCode,CreatedUtc
0,1,NH,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,Concord,Cheshire,New Hampshire,3301,2019-02-14 16:21:52
1,2,NH,29A49AA6-047E-4008-ABBD-3DE57156B526,Concord,Merrimack,New Hampshire,3229,2019-02-14 18:14:30
2,3,MS,9DF11B65-7F29-452C-A69E-54CD72E4A116,Jackson,Rankin,Mississippi,39203,2016-08-19 17:07:23
3,4,VA,693FD55F-5F58-405A-B389-5E78B3406497,Richmond,Richmond (city),Virginia,23219,2016-08-19 18:22:53
4,5,CT,0AC2A866-19CD-4D1A-94B7-BF41A1430553,Wethersfield,Hartford,Connecticut,6410,2016-08-21 01:21:13

In [ ]:
attTimeEntires.head()

,Id,StateAbbr,TimeEntryUno,AttorneyUno,Hours,EnteredOnUtc
0,1,AK,44954D1D-C354-41F6-8C33-327E866B6BA3,C126C566-9039-4991-BDD8-0CDD05C27DDF,1.8,2017-01-05 21:25:23
1,2,AL,F1D8F733-1BDB-47FD-BC7C-CB512E2C5A3A,F8C0E3D3-B3A5-42B9-9E2F-2A637BA83D6E,0.4,2020-03-24 01:10:56
2,3,AR,81ED2628-2FF4-4B67-86B1-F9DFEC603C15,34BFCC3D-B107-4164-B405-DEFF63A65B2D,0.4,2016-12-02 23:21:46
3,4,AZ,14B1BCC4-CEF6-4108-AB54-3CDE482845F0,875DB0F4-619B-4A13-8104-85A3C15D90C4,0.8,2015-12-16 20:32:55
4,5,CA,41275A72-CD69-4A42-85FB-E3E4FEE0C316,22746734-D076-4AC8-BA66-50426C01093C,3.0,2020-09-04 00:02:54

In [ ]:
cat.head()

,Id,StateAbbr,CategoryUno,Category
0,1,AK,4CB7A73E-AAB0-4E8F-94D1-8AC8610AAC64,Consumer Financial Questions
1,2,AL,08C7C59B-6AAE-4BC1-83FE-BC85F1544260,Consumer Financial Questions
2,3,AR,FD5059F7-DE7A-4929-8D67-E72C80773BAD,Consumer Financial Questions
3,4,AZ,D90F1BC7-CD04-409A-9AF7-D4DAB649425A,Consumer Financial Questions
4,5,CA,FD678F86-62B1-4EC4-A628-98AEE7BC74D5,Consumer Financial Questions

In [ ]:
client.head()

,Id,StateAbbr,ClientUno,County,StateName,PostalCode,EthnicIdentity,Age,Gender,MaritalStatus,Veteran,Imprisoned,NumberInHousehold,AnnualIncome,AllowedIncome,CheckingBalance,SavingsBalance,InvestmentsBalance,CreatedUtc
0,1,MS,B731DA7A-A97A-4A2E-BF11-0A126A05AF70,Washington,Mississippi,73179.0,NaN,NaN,NaN,NaN,NaN,No,3.0,26000.0,37190.0,300.0,NaN,NaN,2016-08-25 15:15:37
1,2,MS,8101DB7C-0CC8-4DE9-9E87-71137269AAD5,Harrison,Mississippi,39560.0,Caucasian,NaN,Male,Divorced or Widowed,NaN,No,2.0,52.0,25390.0,1.0,1.0,NaN,2016-08-26 00:55:17
2,3,GA,DD5F1EFC-8298-457F-BC09-CABBEB57A697,Barrow,Georgia,30157.0,Latino or Hispanic,55.0,Male,Single,NaN,No,5.0,3000.0,60790.0,NaN,NaN,NaN,2016-10-12 14:37:06
3,4,TX,21DC9E3D-D0AA-4B85-88BB-428F5BCF7F13,Lubbock,Texas,79416.0,Other,61.0,Female,Married / remarried,No,No,4.0,15600.0,48990.0,100.0,NaN,NaN,2017-01-01 19:57:07
4,5,ID,3782D4F9-9B16-4BC8-ADA3-F85CEE200630,Boise,Idaho,83705.0,Caucasian,65.0,Male,Single,No,No,1.0,15000.0,13590.0,580.0,25.0,NaN,2017-02-23 00:03:27

In [ ]:
questionP.head()

,Id,StateAbbr,QuestionUno,PostText,CreatedUtc
0,1,AK,B7C95D50-6C81-4E61-BC16-81077B7D3F7E,Do you still need help with this issue? It ha...,4/25/18 18:09
1,2,AK,C579CE49-6B7A-44E7-A203-5D3E52623804,"Anyone?,",4/17/18 21:15
2,3,AK,F3A78AD3-D3D4-447F-BEAF-F62F1D1D4CCE,"Yes, those are the right forms. I'm sorry, I ...",4/18/18 17:51
3,4,AK,5F8506D3-D9F1-48EE-8081-D30259DBF4E8,"Hi ###,You do make some good points. The diff...",4/18/18 22:15
4,5,AK,B4C814C9-8983-413F-8BC4-F2BE01665555,My father passed away and I have DNA test resu...,4/12/18 10:52

In [ ]:
questions.head()

,Id,StateAbbr,QuestionUno,CategoryUno,Category,SubcategoryUno,Subcategory,AskedByClientUno,AskedOnUtc,TakenByAttorneyUno,TakenOnUtc,ClosedByAttorneyUno,ClosedOnUtc,LegalDeadline
0,1,NC,BB53B2A4-7C1B-45C3-9693-62047889317D,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,9C35423C-914A-42BC-8EBC-A370E76E2178,2019-06-19 22:10:06,NaN,NaN,NaN,2019-08-13 15:09:06,2019-07-08 00:00:00
1,2,NC,0C49F841-2782-4313-961E-7882B96D0854,C8E1275A-6C42-42E4-9B7D-231BAC438FC9,Individual Rights,73A59926-BA0B-44EC-ABF3-F4C9181EEA83,Civil/Constitutional Rights,DF636AEE-7D08-4F90-9A5C-0A2A726C6B59,2019-06-19 23:34:36,NaN,NaN,NaN,2019-08-13 15:09:14,NaN
2,3,NC,BFC28E08-B6B1-4185-A91A-89DF90816BE4,C8E1275A-6C42-42E4-9B7D-231BAC438FC9,Individual Rights,73A59926-BA0B-44EC-ABF3-F4C9181EEA83,Civil/Constitutional Rights,DF636AEE-7D08-4F90-9A5C-0A2A726C6B59,2019-06-19 23:57:18,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 02:37:16,FA34142B-1575-4720-981C-2D28C3560137,2019-06-24 19:02:35,NaN
3,4,NC,45B24109-243A-489B-B0D2-2F36C2A369FE,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,C9C3FA40-0D60-49B9-97F1-63AFEFAFA484,2019-06-20 02:33:14,FA34142B-1575-4720-981C-2D28C3560137,2019-07-27 18:04:08,FA34142B-1575-4720-981C-2D28C3560137,2019-07-31 05:49:18,NaN
4,5,NC,C4707F71-FE4A-4154-8174-AF00BEE2B361,F6016FBD-9501-4448-BCD3-BBB0E834E33B,Consumer Financial Questions,73FE486E-2B51-456A-A6D9-78A7D05802AA,"Bankruptcy, Debts & Purchases",ED7DEA10-CDB7-4A05-891D-889D1EA710BE,2019-06-20 17:04:47,NaN,NaN,NaN,2019-08-13 15:09:20,NaN

In [ ]:
statesite.head()

,Id,StateAbbr,StateName,AllowedAssets,BaseIncomeLimit,PerHouseholdMemberIncomeLimit,IncomeMultiplier
0,1,AL,Alabama,10000,13590,4720,2.5
1,2,AR,Arkansas,10000,13590,4720,2.5
2,3,AZ,Arizona,10000,13590,4720,2.5
3,4,CA,California,10000,13590,4720,4.0
4,5,CT,Connecticut,10000,13590,4720,2.5

In [ ]:
subcat.head()

,Id,StateAbbr,CategoryUno,SubcategoryUno,Subcategory
0,1,AK,2D43B4FD-FAC8-47C3-A891-085F5D74D64B,546C6AD6-4D2B-4B1D-B09F-8016C5B02D66,COVID-19-Housing
1,2,AK,2D43B4FD-FAC8-47C3-A891-085F5D74D64B,572148E8-96C7-4B74-8280-B749191C5B4C,COVID-19-Insurance
2,3,AK,2D43B4FD-FAC8-47C3-A891-085F5D74D64B,5AA5088E-3A9D-4D99-B6FE-69122C34194A,COVID-19-Lost Documents
3,4,AK,D3504F18-AC99-408B-B1D2-230DC130F9EC,E5DF5CEB-649F-47B3-B665-1BEB3EA4AD42,Emancipation and Delinquency
4,5,AK,BF144F3C-5743-47C5-9EEB-418FF0FAF0D8,16E4350E-BC59-40B7-BF72-0BC225ECA4D1,Immigration

#Extract Unanswered Questions

In [ ]:
nottaken = questions[questions['TakenOnUtc'].isna()]
#nottaken.shape
#questions.shape
nottaken.shape[0] /questions.shape[0] * 100

28.20794660856964

There were 57228 out of 202879 questions not taken by the attorneys. That is 28.2 percent of the questions.

In [ ]:
#nottaken

In [ ]:
grouped = nottaken.groupby(['Category', 'Subcategory'])

grouped.first()

                                                                         Id  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance           1993
                                  Bankruptcy                          11796
                                  Bankruptcy                          49855
                                  Bankruptcy or Debtor Relief Cases  124804
                                  Bankruptcy, Debts & Purchases           5
...                                                                     ...
Work, Employment and Unemployment Work, Employment, or Unemployment  150035
                                  Work/Employment                    186749
                                  Work/Employment/Unemployment           29
                                  Work/Unemployment                  190720
                                  Worker's Comp                      119009

                                                                    StateAbbr  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance               MO
                                  Bankruptcy                               TX
                                  Bankruptcy                               NY
                                  Bankruptcy or Debtor Relief Cases        IN
                                  Bankruptcy, Debts & Purchases            NC
...                                                                       ...
Work, Employment and Unemployment Work, Employment, or Unemployment        NM
                                  Work/Employment                          MS
                                  Work/Employment/Unemployment             NC
                                  Work/Unemployment                        CT
                                  Worker's Comp                            AK

                                                                                              QuestionUno  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         51324C6D-7073-4A73-8C2A-FB5B57A93FF5
                                  Bankruptcy                         6576AEFB-603B-43DE-86C7-95A0D7DBDEBB
                                  Bankruptcy                         B385D21A-D9A9-4CE5-B646-7EC94F00232E
                                  Bankruptcy or Debtor Relief Cases  A62CB07A-DFED-41A5-A5A9-98B352C0185D
                                  Bankruptcy, Debts & Purchases      C4707F71-FE4A-4154-8174-AF00BEE2B361
...                                                                                                   ...
Work, Employment and Unemployment Work, Employment, or Unemployment  10BA589E-438F-4430-B6BA-5EFB5DEF8E1E
                                  Work/Employment                    5DC557C4-F811-4FEF-8B01-05483BDB4C80
                                  Work/Employment/Unemployment       309F5951-B58B-4DA4-A518-B04BCEA409FF
                                  Work/Unemployment                  90FD4022-65C2-409E-B61B-239ACC5BDE3C
                                  Worker's Comp                      00008AE7-5B06-454D-BA0F-969CE8809C33

                                                                                              CategoryUno  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         1EBBF19C-9E26-408A-805A-BC5362E36F28
                                  Bankruptcy                         FA45ADC5-94B4-4597-B167-E715EC0E47E2
                                  Bankruptcy                         0400294A-D08E-437F-8577-A7A0B9D254A0
                                  Bankruptcy or Debtor Relief Cases  09E768DD-114F-47B4-B038-1FE0937EF839
                                  Bankruptcy, Debts & Purchases      F6016FBD-9501-4448-BCD3-BBB0E834E33B
...                                                                                                   ...
Work, Employment and Unemployment Work, Employment, or Unemployment  400F29BE-7D7D-456C-8EE8-C693E8AA433F
                                  Work/Employment                    DEB587B0-8892-461B-9FEE-C2B65331A4C1
                                  Work/Employment/Unemployment       FEE8E86C-A04F-4F6D-97D0-2D8C96ECCD90
                                  Work/Unemployment                  EF1DADC5-831E-4DC1-BD7C-0F652EBF90DB
                                  Worker's Comp                      C2D41B1D-E4E7-44D1-B415-731C5FFA4E5D

                                                                                           SubcategoryUno  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         1AF2BC1C-97F0-4A74-AE52-E6DCB1D979DE
                                  Bankruptcy                         159C4A6E-BAEE-4B08-8F9E-7CEA3BC6B0DF
                                  Bankruptcy                         A27515E5-3789-4A9A-9A31-64293F0A3A2E
                                  Bankruptcy or Debtor Relief Cases  A5B6B6B7-42FA-45A5-8179-4BCE598D7FD2
                                  Bankruptcy, Debts & Purchases      73FE486E-2B51-456A-A6D9-78A7D05802AA
...                                                                                                   ...
Work, Employment and Unemployment Work, Employment, or Unemployment  15AFB7A0-03A5-4AAC-83A9-7AB7A6053BC2
                                  Work/Employment                    A9BE5D0F-1C93-4547-8422-6F225BF46770
                                  Work/Employment/Unemployment       8CEDABC5-E521-46B9-8850-6FC4ED1216A0
                                  Work/Unemployment                  C15FFA0B-B9DE-486F-911A-28A2A9D9926F
                                  Worker's Comp                      4CDDA61F-136A-41D3-80D6-EA0662297CE5

                                                                                         AskedByClientUno  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         F9A4C80E-5BB0-4E01-AA7B-68DD6FFAFE1B
                                  Bankruptcy                         974999DB-05DF-4EA9-9992-5B120A0D3A6C
                                  Bankruptcy                         E16BDA66-1194-4360-B60B-920E4F86BB70
                                  Bankruptcy or Debtor Relief Cases  7FF488DB-2F3F-41C5-AF35-1167A0B337A4
                                  Bankruptcy, Debts & Purchases      ED7DEA10-CDB7-4A05-891D-889D1EA710BE
...                                                                                                   ...
Work, Employment and Unemployment Work, Employment, or Unemployment  8B3DC420-0DEC-4D9A-95D0-DCD96152512D
                                  Work/Employment                    2AB4ABBF-5DB7-4BC1-A056-87AEA209C9A9
                                  Work/Employment/Unemployment       280787CF-ACA1-4C17-AD54-2089B06B27A0
                                  Work/Unemployment                  E4414469-7239-4C3A-AA7F-B6B240E521F7
                                  Worker's Comp                      27A0418D-5F83-4154-8DF9-D1C0DDD85F6F

                                                                              AskedOnUtc  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         2019-01-02 21:40:13
                                  Bankruptcy                         2017-07-03 20:09:34
                                  Bankruptcy                         2021-08-08 15:16:45
                                  Bankruptcy or Debtor Relief Cases  2012-11-21 00:30:45
                                  Bankruptcy, Debts & Purchases      2019-06-20 17:04:47
...                                                                                  ...
Work, Employment and Unemployment Work, Employment, or Unemployment  2017-07-06 19:01:06
                                  Work/Employment                    2017-03-28 14:40:23
                                  Work/Employment/Unemployment       2019-06-25 16:51:36
                                  Work/Unemployment                  2018-10-01 23:08:45
                                  Worker's Comp                      2020-12-09 21:03:32

                                                                    TakenByAttorneyUno  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance                      None
                                  Bankruptcy                                      None
                                  Bankruptcy                                      None
                                  Bankruptcy or Debtor Relief Cases               None
                                  Bankruptcy, Debts & Purchases                   None
...                                                                                ...
Work, Employment and Unemployment Work, Employment, or Unemployment               None
                                  Work/Employment                                 None
                                  Work/Employment/Unemployment                    None
                                  Work/Unemployment                               None
                                  Worker's Comp                                   None

                                                                    TakenOnUtc  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance              None
                                  Bankruptcy                              None
                                  Bankruptcy                              None
                                  Bankruptcy or Debtor Relief Cases       None
                                  Bankruptcy, Debts & Purchases           None
...                                                                        ...
Work, Employment and Unemployment Work, Employment, or Unemployment       None
                                  Work/Employment                         None
                                  Work/Employment/Unemployment            None
                                  Work/Unemployment                       None
                                  Worker's Comp                           None

                                                                                      ClosedByAttorneyUno  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance                                         None
                                  Bankruptcy                                                         None
                                  Bankruptcy                                                         None
                                  Bankruptcy or Debtor Relief Cases  27B73590-F3A5-47DD-A226-B7CD58751722
                                  Bankruptcy, Debts & Purchases                                      None
...                                                                                                   ...
Work, Employment and Unemployment Work, Employment, or Unemployment                                  None
                                  Work/Employment                                                    None
                                  Work/Employment/Unemployment                                       None
                                  Work/Unemployment                                                  None
                                  Worker's Comp                                                      None

                                                                             ClosedOnUtc  \
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         2019-01-02 22:04:15
                                  Bankruptcy                         2017-07-12 13:38:17
                                  Bankruptcy                         2021-09-13 18:41:21
                                  Bankruptcy or Debtor Relief Cases  2012-11-26 02:15:32
                                  Bankruptcy, Debts & Purchases      2019-08-13 15:09:20
...                                                                                  ...
Work, Employment and Unemployment Work, Employment, or Unemployment  2017-07-07 20:25:14
                                  Work/Employment                    2018-03-21 13:51:28
                                  Work/Employment/Unemployment       2019-08-13 15:12:39
                                  Work/Unemployment                  2019-01-31 19:13:19
                                  Worker's Comp                      2021-01-06 00:35:05

                                                                           LegalDeadline
Category                          Subcategory
Consumer Financial Questions      Auto or Property Insurance         2019-02-02 00:00:00
                                  Bankruptcy                         2017-07-17 00:00:00
                                  Bankruptcy                                        None
                                  Bankruptcy or Debtor Relief Cases  2012-12-03 05:00:00
                                  Bankruptcy, Debts & Purchases      2019-07-26 00:00:00
...                                                                                  ...
Work, Employment and Unemployment Work, Employment, or Unemployment  2021-07-26 00:00:00
                                  Work/Employment                    2018-07-29 00:00:00
                                  Work/Employment/Unemployment       2019-06-25 00:00:00
                                  Work/Unemployment                  2019-06-18 00:00:00
                                  Worker's Comp                                     None

[326 rows x 12 columns]

#Preprocessing Question Data

In [ ]:
ques = questions.drop(columns=['Id', 'CategoryUno','SubcategoryUno','AskedByClientUno','AskedOnUtc' ,  'ClosedByAttorneyUno', 'ClosedOnUtc' ])
ques

,StateAbbr,QuestionUno,Category,Subcategory,TakenByAttorneyUno,TakenOnUtc,LegalDeadline
0,NC,BB53B2A4-7C1B-45C3-9693-62047889317D,Family and Children,Family/Divorce/Custody/Visitation/Child Support,NaN,NaN,2019-07-08 00:00:00
1,NC,0C49F841-2782-4313-961E-7882B96D0854,Individual Rights,Civil/Constitutional Rights,NaN,NaN,NaN
2,NC,BFC28E08-B6B1-4185-A91A-89DF90816BE4,Individual Rights,Civil/Constitutional Rights,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 02:37:16,NaN
3,NC,45B24109-243A-489B-B0D2-2F36C2A369FE,Family and Children,Family/Divorce/Custody/Visitation/Child Support,FA34142B-1575-4720-981C-2D28C3560137,2019-07-27 18:04:08,NaN
4,NC,C4707F71-FE4A-4154-8174-AF00BEE2B361,Consumer Financial Questions,"Bankruptcy, Debts & Purchases",NaN,NaN,NaN
...,...,...,...,...,...,...,...
202874,NC,376FFF48-9068-4A8F-9316-2EB5A7E38001,Other,Civil Procedure,6E43EC98-8700-4439-98A9-52B663CCE348,2019-07-17 19:22:29,NaN
202875,NC,98AA49B1-D423-4D12-9E70-A5BD6663DFE5,Other,Civil Procedure,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 03:07:59,2019-06-18 00:00:00
202876,NC,B80305AA-7509-436E-AFF8-6B33AC682730,Other,Civil Procedure,NaN,NaN,2019-06-27 00:00:00
202877,NC,DC374484-7C6E-44A3-9DB7-89B8868518F1,Other,Other,6E43EC98-8700-4439-98A9-52B663CCE348,2019-06-24 14:47:57,2019-07-01 00:00:00
202878,NC,1F2F2FC1-4661-4A14-A7BE-43E883D1BD44,Family and Children,Family/Divorce/Custody/Visitation/Child Support,NaN,NaN,NaN

In [ ]:
questionP

,Id,StateAbbr,QuestionUno,PostText,CreatedUtc
0,1,AK,B7C95D50-6C81-4E61-BC16-81077B7D3F7E,Do you still need help with this issue? It ha...,4/25/18 18:09
1,2,AK,C579CE49-6B7A-44E7-A203-5D3E52623804,"Anyone?,",4/17/18 21:15
2,3,AK,F3A78AD3-D3D4-447F-BEAF-F62F1D1D4CCE,"Yes, those are the right forms. I'm sorry, I ...",4/18/18 17:51
3,4,AK,5F8506D3-D9F1-48EE-8081-D30259DBF4E8,"Hi ###,You do make some good points. The diff...",4/18/18 22:15
4,5,AK,B4C814C9-8983-413F-8BC4-F2BE01665555,My father passed away and I have DNA test resu...,4/12/18 10:52
...,...,...,...,...,...
356767,356954,UT,D1CD238C-4216-4F3D-BFB4-3C8D28C3B8C6,to ensure that the question is clear and not w...,4/25/19 12:44
356768,356955,UT,D1CD238C-4216-4F3D-BFB4-3C8D28C3B8C6,"Looking at your decree, and just generally as ...",4/25/19 16:29
356769,356956,UT,D1CD238C-4216-4F3D-BFB4-3C8D28C3B8C6,Thank you again for your time. Thus far no one...,4/30/19 13:56
356770,356957,UT,B9A70FE8-71CA-42F2-B7D4-8DE07E7DD41D,My neighbors behind me have ###. He recently c...,4/23/19 22:32
356771,356958,UT,B9A70FE8-71CA-42F2-B7D4-8DE07E7DD41D,"Hi ###,Thank you for submitting your question....",5/9/19 23:11

In [ ]:
#qgroup = questionP.groupby('QuestionUno', group_keys=True).apply(lambda x: x)
qPid = questionP['QuestionUno']
qPid.drop_duplicates()

uniqueques = qPid.drop_duplicates()
uniqueques.index

Int64Index([     0,      1,      2,      3,      4,      5,      8,      9,
                10,     11,
            ...
            356744, 356746, 356748, 356750, 356752, 356755, 356757, 356762,
            356764, 356770],
           dtype='int64', length=148238)

In [ ]:
reducedQ = questionP.iloc[uniqueques.index]
reducedQ

,Id,StateAbbr,QuestionUno,PostText,CreatedUtc
0,1,AK,B7C95D50-6C81-4E61-BC16-81077B7D3F7E,Do you still need help with this issue? It ha...,4/25/18 18:09
1,2,AK,C579CE49-6B7A-44E7-A203-5D3E52623804,"Anyone?,",4/17/18 21:15
2,3,AK,F3A78AD3-D3D4-447F-BEAF-F62F1D1D4CCE,"Yes, those are the right forms. I'm sorry, I ...",4/18/18 17:51
3,4,AK,5F8506D3-D9F1-48EE-8081-D30259DBF4E8,"Hi ###,You do make some good points. The diff...",4/18/18 22:15
4,5,AK,B4C814C9-8983-413F-8BC4-F2BE01665555,My father passed away and I have DNA test resu...,4/12/18 10:52
...,...,...,...,...,...
356755,356942,UT,DC4952A1-2508-4ABD-9C23-80C6362FCB87,I made ###. The first order arrived and I assu...,"019-04-20 04:23:23"""
356757,356944,UT,A9C002F9-BFCD-4E6B-AC4A-EA60357DBDA1,I am filing for Chapter ###. I live with my M...,4/22/19 18:56
356762,356949,UT,B1E8E1D9-12A0-477C-869F-93792E6098D0,"To Whom It May Concern,My deceased father was ...",4/22/19 21:05
356764,356951,UT,D1CD238C-4216-4F3D-BFB4-3C8D28C3B8C6,Divorce decree went into affect ######6. Respo...,"019-04-22 23:42:03"""
356770,356957,UT,B9A70FE8-71CA-42F2-B7D4-8DE07E7DD41D,My neighbors behind me have ###. He recently c...,4/23/19 22:32

In [ ]:
#reducedQ.to_csv('/content/drive/Shareddrives/Data Fest 2023/data/reducedQuestions', index=False)

In [ ]:
mergedq = pd.merge(reducedQ, questions, on='QuestionUno')
mergedq = mergedq.drop(columns = ['Id_x', 'StateAbbr_x', 'CreatedUtc','Id_y', 'AskedOnUtc',  'ClosedByAttorneyUno', 'ClosedOnUtc'])

mergedq = mergedq.rename(columns={"StateAbbr_y": "StateAbbr"})
mergedq

,QuestionUno,PostText,StateAbbr,CategoryUno,Category,SubcategoryUno,Subcategory,AskedByClientUno,TakenByAttorneyUno,TakenOnUtc,LegalDeadline
0,B7C95D50-6C81-4E61-BC16-81077B7D3F7E,Do you still need help with this issue? It ha...,AK,2D43B4FD-FAC8-47C3-A891-085F5D74D64B,Housing and Homelessness,6F28DF84-2BDA-48AE-97F8-A083D20E3EC8,Housing or Property Owned,56A7173F-C8B2-4E17-8189-DBDB8EDDAA1C,0293D737-A73B-47D8-8D26-FE5AB33F67E1,2018-04-25 18:08:21,NaN
1,C579CE49-6B7A-44E7-A203-5D3E52623804,"Anyone?,",AK,2D43B4FD-FAC8-47C3-A891-085F5D74D64B,Housing and Homelessness,6F28DF84-2BDA-48AE-97F8-A083D20E3EC8,Housing or Property Owned,6CB2B648-61A3-425F-9B84-A7C637B83126,NaN,NaN,NaN
2,F3A78AD3-D3D4-447F-BEAF-F62F1D1D4CCE,"Yes, those are the right forms. I'm sorry, I ...",AK,A96DEADE-C287-4B31-BFF5-6C02E0640001,Family and Children,372E3CF8-3543-4C71-BA48-DA3F52FC5792,Family/Divorce/Custody,00BB08E8-38C6-42CE-8A01-6C8A1F7F88E7,C4EA5672-72E4-47CD-A4C2-E4A7C874E40A,2018-04-05 23:11:26,2018-04-18 00:00:00
3,5F8506D3-D9F1-48EE-8081-D30259DBF4E8,"Hi ###,You do make some good points. The diff...",AK,E31B199A-B01E-47E6-86DB-8D99B2BB7420,Other,3DBF3B9F-9ED0-4028-A4FE-0823B0012634,Other,6CB2B648-61A3-425F-9B84-A7C637B83126,C4EA5672-72E4-47CD-A4C2-E4A7C874E40A,2018-04-09 18:34:20,NaN
4,B4C814C9-8983-413F-8BC4-F2BE01665555,My father passed away and I have DNA test resu...,AK,A96DEADE-C287-4B31-BFF5-6C02E0640001,Family and Children,BB9683D7-FAE6-4E33-AF74-52E71373C8D7,Wills/Inheritance,2761B481-9CAD-4494-B8CB-27AF221FDA69,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
148203,DC4952A1-2508-4ABD-9C23-80C6362FCB87,I made ###. The first order arrived and I assu...,UT,B4FA50DD-8B47-4BD9-8F78-91E2AF96A31D,Other,290A8D28-2BB6-499F-ACD2-4C3F284587D2,Other,3B8208D2-8246-48EC-8531-03C5150DC87E,66ACB2C6-B4B5-4015-AE1A-4D1E08D17860,2019-05-17 16:10:38,NaN
148204,A9C002F9-BFCD-4E6B-AC4A-EA60357DBDA1,I am filing for Chapter ###. I live with my M...,UT,C955358F-23B0-4BCF-948D-C7AE744536DE,Consumer Financial Questions,853609D4-68B8-4C13-A9CD-50562473A304,Debts & Purchases,4F7851EF-7C2C-4DD6-B1C6-1EA8A37D0735,66ACB2C6-B4B5-4015-AE1A-4D1E08D17860,2019-04-25 15:21:46,NaN
148205,B1E8E1D9-12A0-477C-869F-93792E6098D0,"To Whom It May Concern,My deceased father was ...",UT,B4FA50DD-8B47-4BD9-8F78-91E2AF96A31D,Other,290A8D28-2BB6-499F-ACD2-4C3F284587D2,Other,1A6DFAFF-3DE5-4E38-92B6-C6F24C69FDA8,66ACB2C6-B4B5-4015-AE1A-4D1E08D17860,2019-05-20 14:05:22,NaN
148206,D1CD238C-4216-4F3D-BFB4-3C8D28C3B8C6,Divorce decree went into affect ######6. Respo...,UT,39A338D3-FE08-4A0B-90FA-CEC4DBB2C64F,Family and Children,178DFF3C-856C-4100-B819-9659C3ECFC4E,Family/Divorce/Custody,2C9C84D9-4329-4FD7-9877-6491EFB2DE83,85C0CADA-3E7F-4BE1-B852-DE1D58E7E02F,2019-04-24 16:53:40,NaN
148207,B9A70FE8-71CA-42F2-B7D4-8DE07E7DD41D,My neighbors behind me have ###. He recently c...,UT,55739525-2665-43A6-9242-6A036EE81E55,Housing and Homelessness,796DFA43-55B0-48FA-8204-7B00135305DC,Housing or Property Owned,B75DF747-F207-499E-A2BA-AE95751D95B3,66ACB2C6-B4B5-4015-AE1A-4D1E08D17860,2019-05-09 23:02:12,NaN

In [ ]:
#mergedq.to_csv('/content/drive/Shareddrives/Data Fest 2023/data/MergedQuestions.csv', index=False)

#Attorney Info

In [ ]:
attorney

,Id,StateAbbr,AttorneyUno,City,County,StateName,PostalCode,CreatedUtc
0,1,NH,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,Concord,Cheshire,New Hampshire,3301,2019-02-14 16:21:52
1,2,NH,29A49AA6-047E-4008-ABBD-3DE57156B526,Concord,Merrimack,New Hampshire,3229,2019-02-14 18:14:30
2,3,MS,9DF11B65-7F29-452C-A69E-54CD72E4A116,Jackson,Rankin,Mississippi,39203,2016-08-19 17:07:23
3,4,VA,693FD55F-5F58-405A-B389-5E78B3406497,Richmond,Richmond (city),Virginia,23219,2016-08-19 18:22:53
4,5,CT,0AC2A866-19CD-4D1A-94B7-BF41A1430553,Wethersfield,Hartford,Connecticut,6410,2016-08-21 01:21:13
...,...,...,...,...,...,...,...,...
11539,11540,VA,F2EC8DAD-D7B0-40B8-AFF2-F5705E2F59B0,Washington,Arlington,Virginia,20037,2021-11-03 15:16:31
11540,11541,VA,386CD203-A6E0-4C8F-90D3-0EEEC2701CA3,Virginia Beach,Virginia Beach city,Virginia,23451,2021-11-04 13:56:07
11541,11542,VA,1C366F1B-0990-4847-8B47-D56D426AD964,Virginia Beach,Virginia Beach city,Virginia,23451,2021-11-15 20:31:02
11542,11543,VA,FE8B3662-7C55-416A-B123-C3F9A9F3CAFA,Richmond,Richmond city,Virginia,23225,2021-11-15 23:27:59
11543,11544,VA,164F3C9B-FA80-427B-8172-8A4ECE7DAC24,Richmond,Richmond city,Virginia,23227,2021-11-17 19:26:07

In [ ]:
newq = questions.dropna(subset=['ClosedByAttorneyUno'])
newq = newq.rename(columns={"ClosedByAttorneyUno": "AttorneyUno"})
newq

,Id,StateAbbr,QuestionUno,CategoryUno,Category,SubcategoryUno,Subcategory,AskedByClientUno,AskedOnUtc,TakenByAttorneyUno,TakenOnUtc,AttorneyUno,ClosedOnUtc,LegalDeadline
2,3,NC,BFC28E08-B6B1-4185-A91A-89DF90816BE4,C8E1275A-6C42-42E4-9B7D-231BAC438FC9,Individual Rights,73A59926-BA0B-44EC-ABF3-F4C9181EEA83,Civil/Constitutional Rights,DF636AEE-7D08-4F90-9A5C-0A2A726C6B59,2019-06-19 23:57:18,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 02:37:16,FA34142B-1575-4720-981C-2D28C3560137,2019-06-24 19:02:35,NaN
3,4,NC,45B24109-243A-489B-B0D2-2F36C2A369FE,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,C9C3FA40-0D60-49B9-97F1-63AFEFAFA484,2019-06-20 02:33:14,FA34142B-1575-4720-981C-2D28C3560137,2019-07-27 18:04:08,FA34142B-1575-4720-981C-2D28C3560137,2019-07-31 05:49:18,NaN
8,9,NC,459A9C10-12DF-4548-825D-EB7864457CC6,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,A911AEC6-4E0E-45B3-8807-024EC3C2EADE,Expungement,3A361F5F-C49D-41AF-8BC4-BC211D14D6E1,2019-06-20 21:26:13,9514BCF0-8AD4-4948-B12E-706BBF451492,2019-07-18 17:39:46,9514BCF0-8AD4-4948-B12E-706BBF451492,2019-07-20 22:18:18,NaN
9,10,NC,59D6CCAC-2EA5-4B62-8D38-17C4681DC856,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,8C7CE01E-1EDE-42C4-8C99-0233E565855F,Estate/Wills/Inheritance/Power of Attorney,11262CC7-711D-4387-86D7-975C18DBDB96,2019-06-21 17:32:08,3431BD06-C607-4541-934B-3EBAA71BDBBA,2019-07-08 20:00:18,3431BD06-C607-4541-934B-3EBAA71BDBBA,2019-07-17 20:32:49,NaN
11,12,NC,119A97CE-60C3-412C-ADA1-5893D430BAE2,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,81D88E4F-5B6A-4C9B-BE9A-C4AEAD0B1D7D,Personal Injury,10C82829-7592-4D22-B6AE-D482DABF4074,2019-06-21 21:27:20,9514BCF0-8AD4-4948-B12E-706BBF451492,2019-07-18 17:31:51,9514BCF0-8AD4-4948-B12E-706BBF451492,2019-07-30 15:37:21,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
202867,202868,NC,8CBF4481-97FF-476C-B9F8-077AF707BBA6,C932D197-7F43-4BCF-BE0B-FE5F5DBCB9EF,Family and Children,E9F87919-0CD5-4D9D-AAC6-3CBC49132F1D,Family/Divorce/Custody/Visitation/Child Support,04C05471-0451-4D67-8F9F-6179C3F2D5CF,2019-06-16 19:19:33,C34A900E-E623-46B5-A876-7B3A7C7B4A89,2019-07-10 02:46:40,C34A900E-E623-46B5-A876-7B3A7C7B4A89,2019-07-20 02:47:59,NaN
202869,202870,NC,18992054-FD58-4D53-B37F-21F8DD9E069A,A56CA695-DA51-419F-87CF-228B360F2E9B,Housing and Homelessness,F4BB9A8A-D699-48FD-A6E7-58FB95CC4021,Housing/Eviction/Foreclosure/Tenants,61AA3759-8212-44E5-B6F5-16355978B7A7,2019-06-16 19:51:24,9514BCF0-8AD4-4948-B12E-706BBF451492,2019-07-20 21:16:13,9514BCF0-8AD4-4948-B12E-706BBF451492,2019-07-30 21:17:25,NaN
202874,202875,NC,376FFF48-9068-4A8F-9316-2EB5A7E38001,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,E3257971-6837-4BAD-B00D-E4040F0C8B8A,Civil Procedure,82BDD11F-2168-4A44-BBFC-BA9B0543F289,2019-06-17 20:37:01,6E43EC98-8700-4439-98A9-52B663CCE348,2019-07-17 19:22:29,6E43EC98-8700-4439-98A9-52B663CCE348,2019-07-27 19:26:43,NaN
202875,202876,NC,98AA49B1-D423-4D12-9E70-A5BD6663DFE5,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,E3257971-6837-4BAD-B00D-E4040F0C8B8A,Civil Procedure,FF2959DA-CCA4-415A-BA9B-2D51F860C08D,2019-06-18 13:06:00,FA34142B-1575-4720-981C-2D28C3560137,2019-06-22 03:07:59,FA34142B-1575-4720-981C-2D28C3560137,2019-06-24 19:02:56,2019-06-18 00:00:00
202877,202878,NC,DC374484-7C6E-44A3-9DB7-89B8868518F1,E6F4FD7C-FCE9-4763-AADD-0544158DE0BB,Other,26D3CE4B-3540-477E-BA03-78EF65769A12,Other,A40F8543-330C-43A1-97AC-53C01FD4013E,2019-06-19 03:23:46,6E43EC98-8700-4439-98A9-52B663CCE348,2019-06-24 14:47:57,6E43EC98-8700-4439-98A9-52B663CCE348,2019-06-28 21:59:13,2019-07-01 00:00:00

In [ ]:
att = pd.merge(attorney, newq, on='AttorneyUno')
att
att.to_csv('/content/drive/Shareddrives/Data Fest 2023/data/attorney_cases.csv', index=False)

In [ ]:
#att.to_csv('/content/drive/Shareddrives/Data Fest 2023/data/attorney_cases.csv', index=False)

In [ ]:
g1 = att.groupby('AttorneyUno')['Category'].sum()
g1

AttorneyUno
000B021F-9FBF-4058-8ADC-D0A6232B6C04                             Housing and Homelessness
0023FF7C-934D-4974-87A9-B90BE52D4D5B    Family and ChildrenFamily and ChildrenFamily a...
003C4876-C682-4E94-B161-4BE4B5AD0FBD                                  Family and Children
00401285-58EE-4E39-9807-87A570C4B9ED    Family and ChildrenFamily and ChildrenFamily a...
00609EE0-87BE-496A-9847-A711F4569A25    Housing and HomelessnessFamily and ChildrenFam...
                                                              ...
FF9B1182-D622-4028-BA8F-5911D1E6D809                                  Family and Children
FFC66FAF-38C4-4520-88DE-19BBD7BF5F26    Work, Employment and UnemploymentHousing and H...
FFD551B4-3BB5-4C00-9714-032776657EC0    Family and ChildrenFamily and ChildrenFamily a...
FFDDF712-4C58-4DB5-A63E-99355C6448A0               Family and ChildrenFamily and Children
FFEADD85-31FF-42D4-A8B3-BEF4F180D8FD                         Consumer Financial Questions
Name: Category, Length: 4825, dtype: object

In [ ]:
att['count'] = 1

In [ ]:
att

,Id_x,StateAbbr_x,AttorneyUno,City,County,StateName,PostalCode,CreatedUtc,Id_y,StateAbbr_y,...,Category,SubcategoryUno,Subcategory,AskedByClientUno,AskedOnUtc,TakenByAttorneyUno,TakenOnUtc,ClosedOnUtc,LegalDeadline,count
0,1,NH,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,Concord,Cheshire,New Hampshire,3301,2019-02-14 16:21:52,160969,NH,...,Other,A36C230B-2CD3-40D8-A44D-6D1AAC88DDC0,Other,AD0F0934-9FFE-43CB-B01A-6A3450335442,2019-06-05 10:10:19,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,2019-06-05 19:24:25,2019-06-07 12:10:14,NaN,1
1,1,NH,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,Concord,Cheshire,New Hampshire,3301,2019-02-14 16:21:52,161041,NH,...,Family and Children,789FE53A-EC4F-4BAF-8F8E-7814D2AA8CFC,Family/Divorce/Custody,79A7EFC7-A5D6-4F0F-AEC6-E30F9405BC72,2019-08-29 16:58:57,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,2019-09-09 13:32:38,2019-09-20 10:07:12,NaN,1
2,1,NH,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,Concord,Cheshire,New Hampshire,3301,2019-02-14 16:21:52,161286,NH,...,Family and Children,789FE53A-EC4F-4BAF-8F8E-7814D2AA8CFC,Family/Divorce/Custody,1B6F52CF-304F-44EC-AF8B-A7B3BD9283F8,2020-05-30 11:02:49,7A2C12BE-9F37-4C9D-A6ED-41B916820CE0,2020-06-01 17:29:38,2020-06-04 13:45:28,NaN,1
3,6,LA,231AB5DE-6431-4BAE-BAC3-0E453BFD7062,Covington,St. Tammany Parish,Louisiana,70433,2016-08-16 19:45:15,155969,LA,...,Family and Children,488FD95A-23A5-4313-ACBD-0A300F46608B,Family/Divorce/Custody,C876E564-7C7E-47A3-ADA4-65EA54D8C28A,2016-12-29 04:39:31,231AB5DE-6431-4BAE-BAC3-0E453BFD7062,2017-03-14 21:38:20,2017-03-31 19:15:07,NaN,1
4,6,LA,231AB5DE-6431-4BAE-BAC3-0E453BFD7062,Covington,St. Tammany Parish,Louisiana,70433,2016-08-16 19:45:15,155970,LA,...,Family and Children,488FD95A-23A5-4313-ACBD-0A300F46608B,Family/Divorce/Custody,6EA64518-E088-4D2C-82D4-9B01219C4A4C,2017-01-01 04:33:57,231AB5DE-6431-4BAE-BAC3-0E453BFD7062,2017-02-13 23:14:43,2017-02-26 03:27:12,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137782,11539,VA,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,ALEXANDRIA,Alexandria city,Virginia,22314,2021-11-01 20:06:00,71375,VA,...,Housing and Homelessness,216AA505-1C74-486D-BD3A-0DE059BBD9C0,Housing or Property Owned,1FCE93F3-0DFE-4B9D-860A-9296336A7394,2021-12-13 15:14:02,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,2021-12-14 18:47:50,2021-12-17 21:27:55,NaN,1
137783,11539,VA,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,ALEXANDRIA,Alexandria city,Virginia,22314,2021-11-01 20:06:00,71378,VA,...,Education,5FAD8052-5F15-495E-A82A-147213A900B9,School Discipline,896832C5-252D-4441-B97E-DBA35A606C6D,2021-12-13 18:36:10,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,2021-12-13 18:59:08,2021-12-19 00:07:25,NaN,1
137784,11539,VA,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,ALEXANDRIA,Alexandria city,Virginia,22314,2021-11-01 20:06:00,71407,VA,...,Other,57F80FCA-C17B-42CF-A2BF-4D9E668C876E,Other,562C0178-2D0A-4739-BF64-08EA888915A8,2021-12-22 09:38:40,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,2021-12-23 15:10:39,2021-12-28 03:45:47,NaN,1
137785,11539,VA,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,ALEXANDRIA,Alexandria city,Virginia,22314,2021-11-01 20:06:00,71428,VA,...,"Work, Employment and Unemployment",CF72BA3E-76E5-4830-A54C-2C7E4F46FE5A,Work,5FBC9F25-5B51-4165-B9D2-9AA64C3FC536,2022-01-01 14:53:39,2BD64F66-B14E-4119-9B2F-6B22D6BB98AC,2022-01-01 15:43:58,2022-01-04 14:38:24,NaN,1
137786,11543,VA,FE8B3662-7C55-416A-B123-C3F9A9F3CAFA,Richmond,Richmond city,Virginia,23225,2021-11-15 23:27:59,71421,VA,...,Other,57F80FCA-C17B-42CF-A2BF-4D9E668C876E,Other,0703B521-587C-4127-B37A-FDE8DE563897,2021-12-30 05:02:18,FE8B3662-7C55-416A-B123-C3F9A9F3CAFA,2021-12-30 19:31:38,2022-01-09 20:05:28,NaN,1

In [ ]:
g2 = att.groupby(['AttorneyUno','Category'])['count'].sum()

attcatcount = pd.DataFrame(g2)
attcatcount

                                                                        count
AttorneyUno                          Category
000B021F-9FBF-4058-8ADC-D0A6232B6C04 Housing and Homelessness               1
0023FF7C-934D-4974-87A9-B90BE52D4D5B Family and Children                    3
003C4876-C682-4E94-B161-4BE4B5AD0FBD Family and Children                    1
00401285-58EE-4E39-9807-87A570C4B9ED Family and Children                    3
00609EE0-87BE-496A-9847-A711F4569A25 Family and Children                    4
...                                                                       ...
FFC66FAF-38C4-4520-88DE-19BBD7BF5F26 Work, Employment and Unemployment      1
FFD551B4-3BB5-4C00-9714-032776657EC0 Family and Children                    4
                                     Work, Employment and Unemployment      1
FFDDF712-4C58-4DB5-A63E-99355C6448A0 Family and Children                    2
FFEADD85-31FF-42D4-A8B3-BEF4F180D8FD Consumer Financial Questions           1

[12294 rows x 1 columns]

In [ ]:
#attcatcount.to_csv('/content/drive/Shareddrives/Data Fest 2023/data/attorney_cat_count.csv', index=False)

In [ ]:
attcatcount

                                                                        count
AttorneyUno                          Category
000B021F-9FBF-4058-8ADC-D0A6232B6C04 Housing and Homelessness               1
0023FF7C-934D-4974-87A9-B90BE52D4D5B Family and Children                    3
003C4876-C682-4E94-B161-4BE4B5AD0FBD Family and Children                    1
00401285-58EE-4E39-9807-87A570C4B9ED Family and Children                    3
00609EE0-87BE-496A-9847-A711F4569A25 Family and Children                    4
...                                                                       ...
FFC66FAF-38C4-4520-88DE-19BBD7BF5F26 Work, Employment and Unemployment      1
FFD551B4-3BB5-4C00-9714-032776657EC0 Family and Children                    4
                                     Work, Employment and Unemployment      1
FFDDF712-4C58-4DB5-A63E-99355C6448A0 Family and Children                    2
FFEADD85-31FF-42D4-A8B3-BEF4F180D8FD Consumer Financial Questions           1

[12294 rows x 1 columns]